### ISSUE TITLE
Save you some work

### ISSUE THREAD

**Issue by panoply** [shapedigital/shape-shopify-autocomplete#1]
Hey @shapedigital 

Great stuff here ~ Just wanted to stop by and maybe save you some work. I've mapped the entire Shopify Liquid API - All objects, filters, tags and deeply nested object properties. The completions are provided within [vscode-liquid](https://github.com/panoply/vscode-liquid) and also supply documentation references with descriptions – The brunt of the logic currently exists in [liquid-language-specs](https://www.npmjs.com/package/@liquify/liquid-language-specs) that can be consumed via NPM though is currently still private. 

Here is live example of current completions:

https://user-images.githubusercontent.com/7041324/198712609-eee73057-1abc-461f-a357-7d8271ef3ed7.mov

Hope it helps.

**Comment by shapedigital** [comment]
Hey @panoply.

Congratulations on your extension. I've used it in the past, it's great and far surpasses anything I'm doing here. 

I also don't see what it has to do with me, my repo, or my work, so I'll be closing this.
Good luck in your endeavours. ✌️

**Comment by panoply** [comment]
Hey, you can use the data for your extension is what I mean.
